### ISSUE TITLE
El archivo manage.py no cuenta con las importaciones pertinentes.

### ISSUE THREAD

**Issue by mruwzum** [mruwzum/EGC-1819-1230-migantber#1]
Al ejecutar el servidor, aparece el siguiente error en el terminal:

´´´
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "decide.settings")
NameError: name 'os' is not defined
MacBook-Pro:decide mruwzum$ python3 manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
NameError: name 'sys' is not defined
´´´

Se necesitan importar correctamente las dependencias os y sys.

**Comment by mruwzum** [comment]
Solucionada en el commit: 704bee087dd185dc66630f54e74fb102a3621f40
